changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: "🚀 Features"
      labels:
          - feature
          - enhancement
    - title: "🐛 Bug Fixes"
      labels:
          - fix
          - bugfix
          - bug
    - title: "🧰 Maintenance"
      labels: 
          - chore
    - title: ":package: Dependencies"
      labels:
          - dependencies
          - build
          - dependabot
          - DEPENDABOT