name: "Setup"
description: "Checks out code and installs dependencies using pnpm"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "22"
    - name: Load cache
      uses: actions/cache@v3
      id: pnpm-cache
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install packages
      shell: bash
      run: pnpm install
